### ISSUE TITLE
error from ''from efficientnet import EfficientNetB0''

### ISSUE THREAD

**Issue by shubhaminnani** [qubvel/efficientnet#31]
while running the code

`from efficientnet import EfficientNetB0`

I get error DLL load failed: The specified module could not be found.

tracebook
from efficientnet import EfficientNetB0
Traceback (most recent call last):

  File "<ipython-input-9-d268e9f10551>", line 1, in <module>
    from efficientnet import EfficientNetB0

  File "C:\Users\Student\Anaconda2\lib\site-packages\efficientnet\__init__.py", line 18, in <module>
    `from .preprocessing import center_crop_and_resize, preprocess_input`

  File "C:\Users\Student\Anaconda2\lib\site-packages\efficientnet\preprocessing.py", line 16, in <module>
    `from skimage.transform import resize`

  File "C:\Users\Student\Anaconda2\lib\site-packages\skimage\__init__.py", line 135, in <module>
    `from .data import data_dir`

  File "C:\Users\Student\Anaconda2\lib\site-packages\skimage\data\__init__.py", line 16, in <module>
   ` from ._binary_blobs import binary_blobs
`
  File "C:\Users\Student\Anaconda2\lib\site-packages\skimage\data\_binary_blobs.py", line 2, in <module>
  `  from ..filters import gaussian`

  File "C:\Users\Student\Anaconda2\lib\site-packages\skimage\filters\__init__.py", line 1, in <module>
   ` from .lpi_filter import inverse, wiener, LPIFilter2D`

  File "C:\Users\Student\Anaconda2\lib\site-packages\skimage\filters\lpi_filter.py", line 7, in <module>
    `from scipy.fftpack import ifftshift`

  File "C:\Users\Student\Anaconda2\lib\site-packages\scipy\fftpack\__init__.py", line 99, in <module>
    `from .basic import *`

  File "C:\Users\Student\Anaconda2\lib\site-packages\scipy\fftpack\basic.py", line 12, in <module>
    `**from . import _fftpack**`

**ImportError: DLL load failed: The specified module could not be found.**

**Comment by shubhaminnani** [comment]
@qubvel

**Comment by qubvel** [comment]
Did not test it with tf2.0
