### ISSUE TITLE
error when creating model 

### ISSUE THREAD

**Issue by mosheliv** [qubvel/efficientnet#6]
hi,

Trying to train this. when running :
```
from efficientnet import EfficientNetB0
import keras
from keras.layers import Activation, Dense, Multiply, Input, Flatten, Dropout, Conv2D, BatchNormalization


inp_mask = Input(shape=(512,512,3))
bn_inp = inp_mask
pretrain_model_mask = EfficientNetB0(
input_shape=(512, 512, 3),  #SWITCH
include_top=False,
weights='imagenet',
#        dropout=0.5,
#        pooling='max'
)(bn_inp)

```

I get the following

```
Traceback (most recent call last):
  File "t.py", line 12, in <module>
    weights='imagenet',
  File "/home/m/.local/lib/python2.7/site-packages/efficientnet/model.py", line 380, in EfficientNetB0
    weights=weights, classes=classes)
  File "/home/m/.local/lib/python2.7/site-packages/efficientnet/model.py", line 358, in _get_model_by_name
    model = EfficientNet(input_shape, block_agrs_list, global_params, include_top=include_top)
  File "/home/m/.local/lib/python2.7/site-packages/efficientnet/model.py", line 282, in EfficientNet
    x = MBConvBlock(block_args, global_params)(x)
  File "/home/m/.local/lib/python2.7/site-packages/efficientnet/model.py", line 232, in block
    x = DropConnect(global_params.drop_connect_rate)(x)
  File "/home/m/.local/lib/python2.7/site-packages/efficientnet/layers.py", line 16, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)

```

**Comment by mosheliv** [comment]
seems like it has to do with python 2.7. it works with 3.x

**Comment by mosheliv** [comment]
on the other hand... after one epoch, i get 

```
Traceback (most recent call last):
  File "en_baseline.py", line 359, in <module>
    callbacks=callback_list)
  File "/home/m/.local/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/m/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/m/.local/lib/python3.5/site-packages/keras/engine/training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/m/.local/lib/python3.5/site-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/m/.local/lib/python3.5/site-packages/keras/callbacks.py", line 446, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "/home/m/.local/lib/python3.5/site-packages/keras/engine/network.py", line 1090, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/home/m/.local/lib/python3.5/site-packages/keras/engine/saving.py", line 382, in save_model
    _serialize_model(model, f, include_optimizer)
  File "/home/m/.local/lib/python3.5/site-packages/keras/engine/saving.py", line 83, in _serialize_model
    model_config['config'] = model.get_config()
  File "/home/m/.local/lib/python3.5/site-packages/keras/engine/network.py", line 860, in get_config
    layer_config = layer.get_config()
  File "/home/m/.local/lib/python3.5/site-packages/keras/engine/network.py", line 860, in get_config
    layer_config = layer.get_config()
  File "/home/m/.local/lib/python3.5/site-packages/efficientnet/layers.py", line 37, in get_config
    config['drop_connect_rate'] = drop_connect_rate
NameError: name 'drop_connect_rate' is not defined

```

this is in the full app, with several callbacks defined,

**Comment by mosheliv** [comment]
I think it has to do with 
```
checkpointer = ModelCheckpoint(
    './' + net_name + '-{epoch:02d}-{val_loss:.4f}.model',  #SWITCH
    #'./sn1-{epoch:02d}-{val_loss:.4f}.model',  #SWITCH
    #    './DenseNet201_{epoch:02d}-{val_loss:.4f}.model', #SWITCH
    verbose=2,
    save_best_only=True)

```

**Comment by qubvel** [comment]
Yes, install latest version from git, I have fixed this bug

**Comment by mosheliv** [comment]
Thank you for the quick response!

**Comment by qubvel** [comment]
But be careful with model saving, look at #2
